// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDub9C4mymAoYQMNgp8dY39HT6J9GTs87I',
    appId: '1:753150777389:web:c4e4768525b6c48a8380a4',
    messagingSenderId: '753150777389',
    projectId: 'extreme-accessibility-math',
    authDomain: 'extreme-accessibility-math.firebaseapp.com',
    storageBucket: 'extreme-accessibility-math.firebasestorage.app',
    measurementId: 'G-HPK19DX016',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJosj4mA7NDKyP56PAGb8vDC19Wjd503c',
    appId: '1:753150777389:android:c97a16f88f65ad5b8380a4',
    messagingSenderId: '753150777389',
    projectId: 'extreme-accessibility-math',
    storageBucket: 'extreme-accessibility-math.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd8JLTKCvSxy61bu44axrXQoN_HUb3268',
    appId: '1:753150777389:ios:29a216860eb5b2d08380a4',
    messagingSenderId: '753150777389',
    projectId: 'extreme-accessibility-math',
    storageBucket: 'extreme-accessibility-math.firebasestorage.app',
    iosBundleId: 'extremeaccesibility.math',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd8JLTKCvSxy61bu44axrXQoN_HUb3268',
    appId: '1:753150777389:ios:faad343df9b701378380a4',
    messagingSenderId: '753150777389',
    projectId: 'extreme-accessibility-math',
    storageBucket: 'extreme-accessibility-math.firebasestorage.app',
    iosBundleId: 'extremeaccesibility.math.RunnerTests',
  );
}
